# <CENTER> Pandas Data Integration and Transformation

## MERGING DATA USING PANDAS

In [8]:
import pandas as pd

### Basic Merging:

In [10]:
df1=pd.DataFrame({"id":[1,2,3],
                  "name":["Asha","Binu","Cathy"]})

df2=pd.DataFrame({"id":[1,2,4],
                   "marks":[85,90,75]})

merged_df=pd.merge (df1, df2, on="id")
print(merged_df)

   id  name  marks
0   1  Asha     85
1   2  Binu     90

# <CENTER> Types of joins:

## Inner Join(default)

### only common rows:

In [15]:
pd.merge(df1,df2, on="id", how="inner")

   id  name  marks
0   1  Asha     85
1   2  Binu     90

## Left Join

### All rows from left DataFrame and common from right:

In [16]:
pd.merge(df1,df2, on="id", how="left")

   id   name  marks
0   1   Asha   85.0
1   2   Binu   90.0
2   3  Cathy    NaN

## Right Join

### All rows from right DataFrame and common from left

In [19]:
pd.merge(df1,df2, on="id", how="right")

   id  name  marks
0   1  Asha     85
1   2  Binu     90
2   4   NaN     75

## Outer Join

### All rows from both:

In [21]:
pd.merge(df1,df2, on="id", how="outer")

   id   name  marks
0   1   Asha   85.0
1   2   Binu   90.0
2   3  Cathy    NaN
3   4    NaN   75.0

## Merge on Different Column Names

In [25]:
df1=pd.DataFrame({"id":[1,2,3],
                  "name":["Asha","Binu","Cathy"]})

df2=pd.DataFrame({"student_id":[1,2,4],
                  "marks":[85,90,75]})
merged_df=pd.merge(df1,df2,left_on="id",right_on="student_id")
print(merged_df)

   id  name  student_id  marks
0   1  Asha           1     85
1   2  Binu           2     90

In [27]:
merg1=pd.merge(df1,df2,left_on="id",right_on="student_id" ,how="left")
print(merg1)

   id   name  student_id  marks
0   1   Asha         1.0   85.0
1   2   Binu         2.0   90.0
2   3  Cathy         NaN    NaN

In [28]:
merg2=pd.merge(df1,df2,left_on="id",right_on="student_id" ,how="right")
print(merg2)

    id  name  student_id  marks
0  1.0  Asha           1     85
1  2.0  Binu           2     90
2  NaN   NaN           4     75

In [30]:
merg3=pd.merge(df1,df2,left_on="id",right_on="student_id" ,how="inner")
print(merg3)

   id  name  student_id  marks
0   1  Asha           1     85
1   2  Binu           2     90

In [31]:
merg4=pd.merge(df1,df2,left_on="id",right_on="student_id" ,how="outer")
print(merg4)

    id   name  student_id  marks
0  1.0   Asha         1.0   85.0
1  2.0   Binu         2.0   90.0
2  3.0  Cathy         NaN    NaN
3  NaN    NaN         4.0   75.0

## Concatenation

In [32]:
pd.concat([df1,df2], axis=0)  (row)

    id   name  student_id  marks
0  1.0   Asha         NaN    NaN
1  2.0   Binu         NaN    NaN
2  3.0  Cathy         NaN    NaN
0  NaN    NaN         1.0   85.0
1  NaN    NaN         2.0   90.0
2  NaN    NaN         4.0   75.0

In [33]:
pd.concat([df1,df2], axis=1)

   id   name  student_id  marks
0   1   Asha           1     85
1   2   Binu           2     90
2   3  Cathy           4     75

### Apply

In [38]:
marks=pd.Series([45,60,75,90])
def grade(x):
    if x>=50:
        return "Pass"
    else:
        return "Fail"
print(marks.apply(grade))

0    Fail
1    Pass
2    Pass
3    Pass
dtype: str

### Apply Using Lambda Function

In [42]:
marks=pd.Series([45,60,75,90])
result=marks.apply(lambda x:x+5)
print(result)

0    50
1    65
2    80
3    95
dtype: int64

### Apply()on DataFrame Columns

In [41]:
df=pd.DataFrame({"maths":[80,70,90],
                 "science":[85,60,95]})
print(df.apply(max))

maths      90
science    95
dtype: int64