# <CENTER> Pandas Data Integration and Transformation

In [2]:
import pandas as pd

### Basic Merging

In [8]:
df1=pd.DataFrame({
    "id":[1,2,3,4,5],
    "name":["Anu","Aju","Amal","Meera","Riya"],
    "age":[20,23,21,22,24]
})    
df2=pd.DataFrame({
    "id":[1,2,6,4,9],
    "mark":[50,65,70,60,80],
    "grade":["A+","A","B","A+","A"]
})
df=pd.merge(df1,df2, on="id")
print(df)

   id   name  age  mark grade
0   1    Anu   20    50    A+
1   2    Aju   23    65     A
2   4  Meera   22    60    A+

### inner join(default)

In [10]:
pd.merge(df1,df2, on="id", how="inner")

   id   name  age  mark grade
0   1    Anu   20    50    A+
1   2    Aju   23    65     A
2   4  Meera   22    60    A+

### Left join

In [11]:
pd.merge(df1,df2, on="id" , how="left")

   id   name  age  mark grade
0   1    Anu   20  50.0    A+
1   2    Aju   23  65.0     A
2   3   Amal   21   NaN   NaN
3   4  Meera   22  60.0    A+
4   5   Riya   24   NaN   NaN

### Right join

In [12]:
pd.merge(df1,df2, on="id", how="right")

   id   name   age  mark grade
0   1    Anu  20.0    50    A+
1   2    Aju  23.0    65     A
2   6    NaN   NaN    70     B
3   4  Meera  22.0    60    A+
4   9    NaN   NaN    80     A

### Outer join

In [13]:
pd.merge(df1,df2, on="id", how="outer")

   id   name   age  mark grade
0   1    Anu  20.0  50.0    A+
1   2    Aju  23.0  65.0     A
2   3   Amal  21.0   NaN   NaN
3   4  Meera  22.0  60.0    A+
4   5   Riya  24.0   NaN   NaN
5   6    NaN   NaN  70.0     B
6   9    NaN   NaN  80.0     A

### Merge on Different Column Names

In [3]:
df1=pd.DataFrame({
    "id":[1,2,3,4,5],
    "name":["Anu","Aju","Amal","Meera","Riya"],
    "age":[20,23,21,22,24]
})    
df2=pd.DataFrame({
    "std_id":[1,2,6,4,9],
    "mark":[50,65,70,60,80],
    "grade":["A+","A","B","A+","A"]
})
df=pd.merge(df1,df2, left_on="id",right_on="std_id")
print(df)

   id   name  age  std_id  mark grade
0   1    Anu   20       1    50    A+
1   2    Aju   23       2    65     A
2   4  Meera   22       4    60    A+

In [8]:
merge1=pd.merge(df1,df2,left_on="id",right_on="std_id",how="outer")
print(merge1)

    id   name   age  std_id  mark grade
0  1.0    Anu  20.0     1.0  50.0    A+
1  2.0    Aju  23.0     2.0  65.0     A
2  3.0   Amal  21.0     NaN   NaN   NaN
3  4.0  Meera  22.0     4.0  60.0    A+
4  5.0   Riya  24.0     NaN   NaN   NaN
5  NaN    NaN   NaN     6.0  70.0     B
6  NaN    NaN   NaN     9.0  80.0     A

In [11]:
merge2=pd.merge(df1,df2,left_on="id",right_on="std_id",how="left")
print(merge2)

   id   name  age  std_id  mark grade
0   1    Anu   20     1.0  50.0    A+
1   2    Aju   23     2.0  65.0     A
2   3   Amal   21     NaN   NaN   NaN
3   4  Meera   22     4.0  60.0    A+
4   5   Riya   24     NaN   NaN   NaN

In [13]:
merge3=pd.merge(df1,df2,left_on="id",right_on="std_id",how="right")
print(merge3)

    id   name   age  std_id  mark grade
0  1.0    Anu  20.0       1    50    A+
1  2.0    Aju  23.0       2    65     A
2  NaN    NaN   NaN       6    70     B
3  4.0  Meera  22.0       4    60    A+
4  NaN    NaN   NaN       9    80     A

In [15]:
merge4=pd.merge(df1,df2,left_on="id",right_on="std_id",how="outer")
print(merge4)

    id   name   age  std_id  mark grade
0  1.0    Anu  20.0     1.0  50.0    A+
1  2.0    Aju  23.0     2.0  65.0     A
2  3.0   Amal  21.0     NaN   NaN   NaN
3  4.0  Meera  22.0     4.0  60.0    A+
4  5.0   Riya  24.0     NaN   NaN   NaN
5  NaN    NaN   NaN     6.0  70.0     B
6  NaN    NaN   NaN     9.0  80.0     A

### concatnation

In [16]:
pd.concat([df1,df2], axis=0)

    id   name   age  std_id  mark grade
0  1.0    Anu  20.0     NaN   NaN   NaN
1  2.0    Aju  23.0     NaN   NaN   NaN
2  3.0   Amal  21.0     NaN   NaN   NaN
3  4.0  Meera  22.0     NaN   NaN   NaN
4  5.0   Riya  24.0     NaN   NaN   NaN
0  NaN    NaN   NaN     1.0  50.0    A+
1  NaN    NaN   NaN     2.0  65.0     A
2  NaN    NaN   NaN     6.0  70.0     B
3  NaN    NaN   NaN     4.0  60.0    A+
4  NaN    NaN   NaN     9.0  80.0     A

In [17]:
pd.concat([df1,df2], axis=1)

   id   name  age  std_id  mark grade
0   1    Anu   20       1    50    A+
1   2    Aju   23       2    65     A
2   3   Amal   21       6    70     B
3   4  Meera   22       4    60    A+
4   5   Riya   24       9    80     A